//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mycontact
    {
        public int id { get; set; }
        public string contactname { get; set; }
        public string contactno { get; set; }
        public Nullable<System.DateTime> contactbirthday { get; set; }
        public System.DateTime addondate { get; set; }
        public string contactimage { get; set; }
    }
}
