//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public int role_id { get; set; }
        public bool is_delete { get; set; }
        public bool is_active { get; set; }
        public string email { get; set; }
    
        public virtual role role { get; set; }
    }
}
